spring.application.name=IYS_Backend
server.port=${PORT:8080}

logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger) - %cyan(%msg%n)}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.address=0.0.0.0
server.compression.enabled=false

spring.mvc.async.request-timeout=5000

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=60000

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

spring.security.oauth2.client.registration.google.client-id=${YOUR_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${YOUR_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email
